In [1]:
import pandas as ps

In [2]:
!pip install pandas

Requirement already satisfied: pandas in C:\Python313\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Python313\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Python313\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
#1. Data Loading & Exporting
#import modulename as alias
import pandas as ps

In [4]:
#load the dataset to the notebook
#variablename=read_fileextension(r"file_path")
dataset=ps.read_csv(r"dataset/college_data.csv")

In [5]:
# 2. Previewing & Inspection - check the shape, types, and health of your dataset after loading
# View the first or last n rows of the datase ex- 8
dataset.head(8) #first

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,"75,116","23,070",8.7,9,7.9,8.7,8.8,8.8,9
1,"College of Engineering, Anna University",Tamil nadu,Engineering,"50,000","50,000",8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,"1,49,250","99,250",8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,"1,98,000","1,83,000",8.3,8.3,8,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,"2,60,000","1,70,000",7.2,6.5,6.6,6.9,7.6,7.1,8.3
5,SSN College of Engineering,Tamil nadu,Engineering,"50,000","50,000",8.6,8.9,7.6,8.7,9.1,8.3,8.8
6,"SASTRA University, Thanjavur",Tamil nadu,Engineering,"1,67,000","1,57,000",8.1,8.5,7,8.2,8.3,8.7,8.1
7,P.S.G College of Technology,Tamil nadu,Engineering,"87,000","1,54,000",9,9.2,8.7,8.9,9,9.1,8.8

In [6]:
dataset.tail(8) #from last

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
6781,"Dr. B R Ambedkar Institute of Technology, Port...",Andaman,Hotel-management,"4,780","11,980",--,--,--,--,--,--,--
6782,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Agriculture,939,--,6.6,8.5,5,7,7.5,2.5,9
6783,Andaman & Nicobar Islands Institute of Medical...,Andaman,Medical,"91,050",--,8.3,8.6,8.4,8.4,8.3,8.2,8.1
6784,"Plastindia International University, Dadra & N...",Dadra,Engineering,--,--,--,--,--,--,--,--,--
6785,SSR Institute of Management and Research,Dadra,Management,"1,30,000",--,8,--,--,8,--,6,--
6786,Institute of Hotel Management and Catering Tec...,Dadra,Hotel-management,"77,000",--,7.7,7,7,8.2,8.5,8,7.4
6787,"Government Polytechnic, Daman",Daman,Engineering,"3,575","8,280",--,--,--,--,--,--,--
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,"75,116","23,070",8.7,9,7.9,8.7,8.8,8.8,9

In [7]:
# Displays a summary of the columns, data types, and count of non-null values.
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6789 entries, 0 to 6788
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   College_Name    6789 non-null   str
 1   State           6789 non-null   str
 2   Stream          6789 non-null   str
 3   UG_fee          6789 non-null   str
 4   PG_fee          6789 non-null   str
 5   Rating          6789 non-null   str
 6   Academic        6789 non-null   str
 7   Accommodation   6789 non-null   str
 8   Faculty         6789 non-null   str
 9   Infrastructure  6789 non-null   str
 10  Placement       6789 non-null   str
 11  Social_Life     6789 non-null   str
dtypes: str(12)
memory usage: 636.6 KB

In [8]:
#change datatypes str to number 
#dataset["UG_fee "] = dataset["Age"].astype(int) - for only dataset contain valid integers not a NaN is in dataset
#dataset["UG_fee "] = pd.to_numeric(dataset["Age"], errors="coerce") - if dataset contain invalid values then //best

#if comma is present in dataset
dataset[["UG_fee", "PG_fee"]] = (
    dataset[["UG_fee", "PG_fee"]]
    .replace(",", "", regex=True)
    .apply(ps.to_numeric, errors="coerce")
)

In [9]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6789 entries, 0 to 6788
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   College_Name    6789 non-null   str
 1   State           6789 non-null   str
 2   Stream          6789 non-null   str
 3   UG_fee          5619 non-null   float64
 4   PG_fee          3478 non-null   float64
 5   Rating          6789 non-null   str
 6   Academic        6789 non-null   str
 7   Accommodation   6789 non-null   str
 8   Faculty         6789 non-null   str
 9   Infrastructure  6789 non-null   str
 10  Placement       6789 non-null   str
 11  Social_Life     6789 non-null   str
dtypes: float64(2), str(10)
memory usage: 636.6 KB

In [10]:
columns = ["Rating", "Academic", "Accommodation","Faculty","Infrastructure","Placement","Social_Life"]

dataset[columns] = dataset[columns].apply(
    ps.to_numeric, errors="coerce"
)

In [11]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6789 entries, 0 to 6788
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   College_Name    6789 non-null   str
 1   State           6789 non-null   str
 2   Stream          6789 non-null   str
 3   UG_fee          5619 non-null   float64
 4   PG_fee          3478 non-null   float64
 5   Rating          6057 non-null   float64
 6   Academic        5943 non-null   float64
 7   Accommodation   5900 non-null   float64
 8   Faculty         5882 non-null   float64
 9   Infrastructure  5873 non-null   float64
 10  Placement       5899 non-null   float64
 11  Social_Life     5835 non-null   float64
dtypes: float64(9), str(3)
memory usage: 636.6 KB

In [12]:
# Generates descriptive statistics (mean, min, max, quartiles) for numerical columns
dataset.describe()

,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
count,5.619000e+03,3.478000e+03,6057.000000,5943.000000,5900.000000,5882.000000,5873.000000,5899.000000,5835.000000
mean,1.122684e+05,1.214165e+05,7.810038,8.142571,7.274508,8.123478,7.962251,7.235057,7.938389
std,2.231395e+05,3.276344e+05,0.792908,0.733461,1.056196,0.730003,0.890070,1.261933,0.889822
min,2.650000e+02,2.000000e+02,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.117500e+04,2.565000e+04,7.400000,7.800000,6.800000,7.800000,7.500000,6.600000,7.500000
50%,5.940000e+04,6.300000e+04,7.900000,8.200000,7.400000,8.200000,8.000000,7.500000,8.100000
75%,1.125000e+05,1.139500e+05,8.300000,8.600000,8.000000,8.600000,8.600000,8.100000,8.500000
max,5.000000e+06,8.230000e+06,10.000000,9.800000,9.800000,9.900000,9.900000,9.900000,9.900000

In [13]:
# An attribute (not a method) that returns a tuple representing the number of rows and columns.
dataset.shape

(6789, 12)

In [14]:
# 3. Selection & Filtering - Extract specific subsets of your data using labels, positions, or conditions.
# Select rows and columns strictly by their text labels or a boolean array.
#dataset.loc[row,column]
dataset.loc[:,"State"]

0       Tamil nadu
1       Tamil nadu
2       Tamil nadu
3       Tamil nadu
4       Tamil nadu
           ...
6784         Dadra
6785         Dadra
6786         Dadra
6787         Daman
6788    Tamil nadu
Name: State, Length: 6789, dtype: str

In [15]:
#select multiple columns
dataset.loc[:,["College_Name","State","Placement"]]

                                           College_Name       State  Placement
0                Indian Institute of Technology Madras   Tamil nadu        8.8
1              College of Engineering, Anna University   Tamil nadu        8.3
2                          NIT Trichy, Tiruchirappalli   Tamil nadu        8.8
3                      Vellore Institute of Technology   Tamil nadu        8.5
4                 SRM Engineering College, Kanchipuram   Tamil nadu        7.1
...                                                 ...         ...        ...
6784  Plastindia International University, Dadra & N...       Dadra        NaN
6785          SSR Institute of Management and Research        Dadra        6.0
6786  Institute of Hotel Management and Catering Tec...       Dadra        8.0
6787                     Government Polytechnic, Daman        Daman        NaN
6788             Indian Institute of Technology Madras   Tamil nadu        8.8

[6789 rows x 3 columns]

In [16]:
#Select a specific row by index
dataset.loc[0]

College_Name      Indian Institute of Technology Madras
State                                         Tamil nadu
Stream                                       Engineering
UG_fee                                           75116.0
PG_fee                                           23070.0
Rating                                               8.7
Academic                                             9.0
Accommodation                                        7.9
Faculty                                              8.7
Infrastructure                                       8.8
Placement                                            8.8
Social_Life                                          9.0
Name: 0, dtype: object

In [17]:
#Select specific rows and columns
dataset.loc[0:1, ["College_Name", "Placement"]]

                               College_Name  Placement
0    Indian Institute of Technology Madras         8.8
1  College of Engineering, Anna University         8.3

In [18]:
# Filter rows using a condition
dataset.loc[dataset["Placement"] > 8]

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
5,SSN College of Engineering,Tamil nadu,Engineering,50000.0,50000.0,8.6,8.9,7.6,8.7,9.1,8.3,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...
6721,Jawaharlal Nehru Institute of Medical Sciences,Manipur,Medical,NaN,NaN,8.5,8.5,8.5,9.0,8.5,8.5,8.0
6775,"Tagore Government College of Education, Port B...",Andaman,Science,NaN,NaN,9.0,9.0,NaN,NaN,9.0,9.0,NaN
6780,"Tagore Government College of Education, Port B...",Andaman,Arts,NaN,NaN,9.0,9.0,NaN,NaN,9.0,9.0,NaN
6783,Andaman & Nicobar Islands Institute of Medical...,Andaman,Medical,91050.0,NaN,8.3,8.6,8.4,8.4,8.3,8.2,8.1
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [19]:
# Filter rows and select a column
dataset.loc[dataset["UG_fee"] > 75000, "College_Name"]

0                  Indian Institute of Technology Madras
2                            NIT Trichy, Tiruchirappalli
3                        Vellore Institute of Technology
4                   SRM Engineering College, Kanchipuram
6                           SASTRA University, Thanjavur
                              ...
6728                    National Institute of Technology
6783    Andaman & Nicobar Islands Institute of Medical...
6785            SSR Institute of Management and Research
6786    Institute of Hotel Management and Catering Tec...
6788               Indian Institute of Technology Madras
Name: College_Name, Length: 2241, dtype: str

In [20]:
dataset.loc[dataset["UG_fee"] > 75000,"College_Name"].count()

np.int64(2241)

In [21]:
# Select rows and columns using integer-based positioning (0-indexed).
dataset.iloc[2] #select third row because index starts from 0.

College_Name      NIT Trichy, Tiruchirappalli
State                               Tamil nadu
Stream                             Engineering
UG_fee                                149250.0
PG_fee                                 99250.0
Rating                                     8.5
Academic                                   8.6
Accommodation                              7.8
Faculty                                    8.2
Infrastructure                             8.7
Placement                                  8.8
Social_Life                                8.7
Name: 2, dtype: object

In [22]:
#select first three rows 
dataset.iloc[0:3]

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7

In [23]:
# Select first 2 and 3 rows 
dataset.iloc[0:2, 0:3]

                               College_Name       State       Stream
0    Indian Institute of Technology Madras   Tamil nadu  Engineering
1  College of Engineering, Anna University   Tamil nadu  Engineering

In [24]:
# Select a particular cell
dataset.iloc[1,2]
# row position = 1
# column position = 2

'Engineering'

In [25]:
#Select specific rows 
dataset.iloc[[0, 2, 4]] #prints 1,3 and 5th row (indexing starts from 0.)

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3

In [26]:
# Query columns using a boolean string expression - filter rows using a condtion 
dataset.query("UG_fee > 149250")

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
6,"SASTRA University, Thanjavur",Tamil nadu,Engineering,167000.0,157000.0,8.1,8.5,7.0,8.2,8.3,8.7,8.1
10,Karunya Institute of Technology and Sciences,Tamil nadu,Engineering,213500.0,121500.0,7.9,7.9,7.9,7.9,8.5,7.5,7.4
15,Hindustan Institute of Technology and Science,Tamil nadu,Engineering,229500.0,125500.0,7.6,7.8,6.9,7.8,7.9,6.9,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6662,Sikkim Manipal Institute of Medical Sciences,Sikkim,Medical,1700000.0,98000.0,7.1,7.6,6.2,7.8,6.9,7.5,6.8
6666,Sikkim Manipal College of Physiotherapy,Sikkim,Medical,150000.0,220000.0,8.5,9.0,8.0,9.0,8.0,9.0,8.0
6668,Vinayaka Missions Sikkim University,Sikkim,Pharmacy,176000.0,NaN,7.8,7.8,7.8,8.0,7.8,7.5,7.8
6672,Indian Institute of Information Technology,Manipur,Engineering,187945.0,21795.0,6.8,7.1,6.7,7.6,6.3,6.6,6.2
6678,"Bir Tikendrajit University, Imphal",Manipur,Engineering,160000.0,160000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
dataset.query("UG_fee >150000 and PG_fee>100000")

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
6,"SASTRA University, Thanjavur",Tamil nadu,Engineering,167000.0,157000.0,8.1,8.5,7.0,8.2,8.3,8.7,8.1
10,Karunya Institute of Technology and Sciences,Tamil nadu,Engineering,213500.0,121500.0,7.9,7.9,7.9,7.9,8.5,7.5,7.4
15,Hindustan Institute of Technology and Science,Tamil nadu,Engineering,229500.0,125500.0,7.6,7.8,6.9,7.8,7.9,6.9,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6545,Vinayaka Missions Medical College and Hospital,Puducherry,Medical,1868550.0,3350000.0,8.1,8.5,7.5,8.5,7.7,8.1,8.2
6610,"Tripura Medical College, West Tripura",Tripura,Medical,1140920.0,1013110.0,7.4,7.8,5.8,7.7,7.2,9.3,6.8
6616,Sikkim Manipal University,Sikkim,Engineering,260000.0,174000.0,7.4,7.9,6.5,8.2,7.6,6.8,7.4
6625,Sikkim Manipal Institute of Technology,Sikkim,Management,275000.0,128000.0,8.7,8.7,8.5,8.6,8.9,8.5,8.7
6678,"Bir Tikendrajit University, Imphal",Manipur,Engineering,160000.0,160000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
dataset.query("State == 'Tamil nadu'")

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
4149,"Government Law College, Coimbatore",Tamil nadu,Law,1255.0,1845.0,8.6,9.4,8.4,8.7,9.0,8.1,8.1
4150,"Government Law College, Tiruchirappalli",Tamil nadu,Law,1459.0,1999.0,9.2,9.0,9.0,NaN,NaN,NaN,NaN
4151,"The Tamil Nadu Dr. Ambedkar Law University,",Tamil nadu,Law,38200.0,69620.0,8.2,8.8,7.7,8.6,7.8,7.7,8.4
4152,"Periyar University, Salem",Tamil nadu,Law,NaN,NaN,8.0,8.6,7.0,8.3,8.0,7.9,8.4
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [29]:
dataset.query("College_Name == 'SASTRA University, Thanjavur'")

Empty DataFrame
Columns: [College_Name, State, Stream, UG_fee, PG_fee, Rating, Academic, Accommodation, Faculty, Infrastructure, Placement, Social_Life]
Index: []

In [30]:
# Filter rows based on whether their values exist inside a provided list
dataset[
    dataset["College_Name"].isin([
        "SASTRA University, Thanjavur"
    ])
]

Empty DataFrame
Columns: [College_Name, State, Stream, UG_fee, PG_fee, Rating, Academic, Accommodation, Faculty, Infrastructure, Placement, Social_Life]
Index: []

In [31]:
# isin() — check whether values belong to a list
dataset[dataset["State"].isin(["Tamil nadu", "Sikkim"])]

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
6667,"Himalayan Pharmacy Institute, East Sikkim",Sikkim,Pharmacy,NaN,NaN,7.4,8.4,5.9,8.1,7.4,8.6,5.9
6668,Vinayaka Missions Sikkim University,Sikkim,Pharmacy,176000.0,NaN,7.8,7.8,7.8,8.0,7.8,7.5,7.8
6669,"ICFAI University, Gangtok",Sikkim,Law,78000.0,NaN,6.8,6.7,6.8,7.0,6.7,7.0,6.6
6670,"Sikkim University, Gangtok",Sikkim,Law,15262.0,16102.0,8.4,9.0,8.3,8.9,7.4,8.1,8.5
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [32]:
#for checking SASTRA University, Thanjavur is present in dataset or not   //contains()
print(dataset[dataset["College_Name"].str.contains("SASTRA", case=False, na=False)]["College_Name"].tolist())

['SASTRA University, Thanjavur ', 'SASTRA University, Thanjavur ', 'SASTRA University, Thanjavur ']

In [33]:
#finding unique value present in column College Name 
dataset["College_Name"].unique()

<StringArray>
[                    'Indian Institute of Technology Madras ',
                   'College of Engineering, Anna University ',
                               'NIT Trichy, Tiruchirappalli ',
                           'Vellore Institute of Technology ',
                      'SRM Engineering College, Kanchipuram ',
                                'SSN College of Engineering ',
                              'SASTRA University, Thanjavur ',
                               'P.S.G College of Technology ',
                        'Thiagarajar College of Engineering ',
                        'Coimbatore Institute of Technology ',
 ...
                     'Government J.Thankima College, Aizawl ',
                                     'Zoram Medical College ',
      'Dr. B R Ambedkar Institute of Technology, Port Blair ',
                   'Jawaharlal Nehru Rajkeeya Mahavidyalaya ',
             'Mahatma Gandhi Government College, Mayabander ',
        'Tagore Government College of Education, Port Blair ',
   'Andaman & Nicobar Islands Institute of Medical Sciences ',
 'Plastindia International University, Dadra & Nagar Haveli ',
                  'SSR Institute of Management and Research ',
                             'Government Polytechnic, Daman ']
Length: 3120, dtype: str

In [34]:
#removing extra whitespace from dataset 
dataset["College_Name"] = dataset["College_Name"].str.strip()

In [35]:
dataset[
    dataset["College_Name"].isin([
        "SASTRA University, Thanjavur"
    ])
]

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
6,"SASTRA University, Thanjavur",Tamil nadu,Engineering,167000.0,157000.0,8.1,8.5,7.0,8.2,8.3,8.7,8.1
1397,"SASTRA University, Thanjavur",Tamil nadu,Commerce,47000.0,54750.0,8.1,8.5,7.0,8.2,8.3,8.7,8.1
4129,"SASTRA University, Thanjavur",Tamil nadu,Law,137000.0,137000.0,8.1,8.5,7.0,8.2,8.3,8.7,8.1

In [36]:
# 4. Data Cleaning & Transformation - Handle missing data, duplicates, and structurally alter column values.
#     dataset.isnull() / dataset.isna() - Check for missing or NaN values across the dataset 
dataset.isnull()

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
6784,False,False,False,True,True,True,True,True,True,True,True,True
6785,False,False,False,False,True,False,True,True,False,True,False,True
6786,False,False,False,False,True,False,False,False,False,False,False,False
6787,False,False,False,False,False,True,True,True,True,True,True,True
6788,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
# for counting columns has how many null values.
dataset.isna().sum()

College_Name         0
State                0
Stream               0
UG_fee            1170
PG_fee            3311
Rating             732
Academic           846
Accommodation      889
Faculty            907
Infrastructure     916
Placement          890
Social_Life        954
dtype: int64

In [38]:
#create a copy of your datset 
clean_dataset = dataset.copy()

In [39]:
# check  duplicate rows from the DataFrame.
clean_dataset.duplicated().sum()

np.int64(1)

In [40]:
#remove duplicates 
clean_dataset.drop_duplicates()

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
6783,Andaman & Nicobar Islands Institute of Medical...,Andaman,Medical,91050.0,NaN,8.3,8.6,8.4,8.4,8.3,8.2,8.1
6784,"Plastindia International University, Dadra & N...",Dadra,Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6785,SSR Institute of Management and Research,Dadra,Management,130000.0,NaN,8.0,NaN,NaN,8.0,NaN,6.0,NaN
6786,Institute of Hotel Management and Catering Tec...,Dadra,Hotel-management,77000.0,NaN,7.7,7.0,7.0,8.2,8.5,8.0,7.4
6787,"Government Polytechnic, Daman",Daman,Engineering,3575.0,8280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Remove rows or columns that contain missing values
# clean_dataset.dropna(axis=0)  # Remove rows
# clean_dataset.dropna(axis=1)  # Remove columns
clean_dataset.dropna()

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
6764,Mizoram University,Mizoram,Agriculture,7930.0,12500.0,8.0,8.7,7.0,8.8,8.0,7.6,7.9
6773,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Science,939.0,1128.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6776,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Commerce,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6778,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Arts,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [42]:
#want to modify original dataset
clean_dataset.dropna(inplace=True)

In [43]:
clean_dataset.shape

(3196, 12)

In [44]:
clean_dataset.dropna(axis=0)

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
6764,Mizoram University,Mizoram,Agriculture,7930.0,12500.0,8.0,8.7,7.0,8.8,8.0,7.6,7.9
6773,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Science,939.0,1128.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6776,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Commerce,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6778,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Arts,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [45]:
# df.fillna(value)
# fillna() is used to replace missing (NaN) values.
clean_dataset.fillna(0)

,College_Name,State,Stream,UG_fee,PG_fee,Rating,Academic,Accommodation,Faculty,Infrastructure,Placement,Social_Life
0,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0
1,"College of Engineering, Anna University",Tamil nadu,Engineering,50000.0,50000.0,8.4,8.7,7.7,8.1,8.7,8.3,8.7
2,"NIT Trichy, Tiruchirappalli",Tamil nadu,Engineering,149250.0,99250.0,8.5,8.6,7.8,8.2,8.7,8.8,8.7
3,Vellore Institute of Technology,Tamil nadu,Engineering,198000.0,183000.0,8.3,8.3,8.0,7.8,8.9,8.5,8.5
4,"SRM Engineering College, Kanchipuram",Tamil nadu,Engineering,260000.0,170000.0,7.2,6.5,6.6,6.9,7.6,7.1,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...
6764,Mizoram University,Mizoram,Agriculture,7930.0,12500.0,8.0,8.7,7.0,8.8,8.0,7.6,7.9
6773,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Science,939.0,1128.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6776,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Commerce,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6778,Jawaharlal Nehru Rajkeeya Mahavidyalaya,Andaman,Arts,843.0,1008.0,6.6,8.5,5.0,7.0,7.5,2.5,9.0
6788,Indian Institute of Technology Madras,Tamil nadu,Engineering,75116.0,23070.0,8.7,9.0,7.9,8.7,8.8,8.8,9.0

In [46]:
# Replace column  using a specific values
clean_dataset["UG_fee"] = clean_dataset["UG_fee"].fillna(clean_dataset["UG_fee"].mean())

In [47]:
# apply() is used to apply a function to values in a DataFrame or Series.
# ncrease all fees by 10%
clean_dataset["UG_fee"] = clean_dataset["UG_fee"].apply(lambda x: x * 1.10)

In [48]:
# 5. Aggregation & GroupingSummarize data metrics by segmenting your columns
# dataset.groupby() - Groups rows based on one or more columns so you can perform calculations on each group
clean_dataset.groupby("College_Name")["UG_fee"].mean()

College_Name
A.G & S.G Siddhartha Degree College of                               4085.400000
A.K.K. New Law Academy, Pune                                        23100.000000
A.V. College of Arts Science and Commerce                           22845.166667
ABES Engineering College, Ghaziabad                                158070.000000
AIMS Institutes, Bangalore                                         207900.000000
                                                                       ...
Yashwantrao Chavan Maharashtra Open University- [YCMOU], Nashik     11275.000000
Yashwantrao Mohite College, Pune                                    11550.000000
Yenepoya Dental College                                            660000.000000
Yenepoya University, Mangalore                                      65450.000000
Yeshwantrao Chavan College of Engineering                          166981.100000
Name: UG_fee, Length: 1502, dtype: float64

In [49]:
# dataset.agg()	Applies one or multiple aggregation functions, such as sum, mean, min, or max
clean_dataset.groupby("College_Name")["UG_fee"].agg(["mean", "max", "min"])

,mean,max,min
College_Name,,,
A.G & S.G Siddhartha Degree College of,4085.400000,4085.4,4085.4
"A.K.K. New Law Academy, Pune",23100.000000,23100.0,23100.0
A.V. College of Arts Science and Commerce,22845.166667,24865.5,18804.5
"ABES Engineering College, Ghaziabad",158070.000000,158070.0,158070.0
"AIMS Institutes, Bangalore",207900.000000,250800.0,163900.0
...,...,...,...
"Yashwantrao Chavan Maharashtra Open University- [YCMOU], Nashik",11275.000000,15950.0,6600.0
"Yashwantrao Mohite College, Pune",11550.000000,11550.0,11550.0
Yenepoya Dental College,660000.000000,660000.0,660000.0
"Yenepoya University, Mangalore",65450.000000,66000.0,64900.0
Yeshwantrao Chavan College of Engineering,166981.100000,166981.1,166981.1

In [50]:
# dataset.transform() 	Performs calculations within groups while keeping the same number of rows as the original DataFrame
clean_dataset.groupby("College_Name")["UG_fee"].transform("mean")

0        82627.600000
1        55000.000000
2       135575.000000
3       125400.000000
4       286000.000000
            ...
6764     20940.333333
6773       962.500000
6776       962.500000
6778       962.500000
6788     82627.600000
Name: UG_fee, Length: 3196, dtype: float64

In [51]:
# dataset.value_counts(): Count the occurrences of unique values within a single column.
clean_dataset["College_Name"].value_counts()

College_Name
Indian Institute of Technology                    44
National Institute of Technology                  44
Panjab University                                 21
Indian Institute of Management                    19
Amity University, Noida                           17
                                                  ..
Sikkim Manipal College of Physiotherapy            1
Manipur Institute of Technology                    1
National Sports University                         1
Regional Institute of Medical Sciences, Imphal     1
Aizawl Theological College-[ATC], Aizawl           1
Name: count, Length: 1502, dtype: int64

In [52]:
# 6. Reshaping & Combining
# These pandas functions are used to combine datasets or change the structure/orientation of a DataFrame.
    
# ps.merge()	- Joins two DataFrames using common columns/keys - 	Join tables (inner, Outer , Right join, Left Join)
#     ps.merge(dataset1, dataset2, on="ID", how="inner")
    
# ps.concat()	- Combines DataFrames vertically or horizontally	- Stack tables
#     ps.concat([dataset1, dataset2], axis=0) // for row
#     ps.concat([dataset1, dataset2], axis=1) // for column

# dataset.pivot_table()	- Creates a summarized table using rows, columns, and aggregation - 	Summarize & reshape
clean_dataset.pivot_table( values="UG_fee",index="College_Name", columns="State",aggfunc="sum")

State,Andaman,Andhra pradesh,Arunachal pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Delhi ncr,Goa,Gujarat,...,Puducherry,Punjab,Rajasthan,Sikkim,Tamil nadu,Telangana,Tripura,Uttar pradesh,Uttarakhand,West bengal
College_Name,,,,,,,,,,,,,,,,,,,,,
A.G & S.G Siddhartha Degree College of,NaN,4085.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"A.K.K. New Law Academy, Pune",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.V. College of Arts Science and Commerce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68535.5,NaN,NaN,NaN,NaN
"ABES Engineering College, Ghaziabad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158070.0,NaN,NaN
"AIMS Institutes, Bangalore",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yashwantrao Chavan Maharashtra Open University- [YCMOU], Nashik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yashwantrao Mohite College, Pune",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yenepoya Dental College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yenepoya University, Mangalore",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yeshwantrao Chavan College of Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
clean_dataset.columns

Index(['College_Name', 'State', 'Stream', 'UG_fee', 'PG_fee', 'Rating',
       'Academic', 'Accommodation', 'Faculty', 'Infrastructure', 'Placement',
       'Social_Life'],
      dtype='str')

In [54]:
clean_dataset.melt(id_vars=["College_Name"],var_name="Column",value_name="Value")

                                  College_Name       Column       Value
0        Indian Institute of Technology Madras        State  Tamil nadu
1      College of Engineering, Anna University        State  Tamil nadu
2                  NIT Trichy, Tiruchirappalli        State  Tamil nadu
3              Vellore Institute of Technology        State  Tamil nadu
4         SRM Engineering College, Kanchipuram        State  Tamil nadu
...                                        ...          ...         ...
35151                       Mizoram University  Social_Life         7.9
35152  Jawaharlal Nehru Rajkeeya Mahavidyalaya  Social_Life         9.0
35153  Jawaharlal Nehru Rajkeeya Mahavidyalaya  Social_Life         9.0
35154  Jawaharlal Nehru Rajkeeya Mahavidyalaya  Social_Life         9.0
35155    Indian Institute of Technology Madras  Social_Life         9.0

[35156 rows x 3 columns]

In [55]:
# dataset.melt()- 	Converts wide-format data into long-format data - Unpivot / widen → long
# clean_dataset.melt(id_vars=["College_Name"],var_name="State",value_name="Value")

# Simple example - //Before melting 
# Name    Math    Science    English
# A       90      80         85
# B       70      75         88
# This is wide format because Math, Science, and English are separate columns.
df = ps.DataFrame({
    "Name": ["A", "B"],
    "Math": [90, 70],
    "Science": [80, 75],
    "English": [85, 88]
})

print(df)

  Name  Math  Science  English
0    A    90       80       85
1    B    70       75       88

In [56]:
df.melt(id_vars="Name",var_name="Subject",value_name="Marks")

  Name  Subject  Marks
0    A     Math     90
1    B     Math     70
2    A  Science     80
3    B  Science     75
4    A  English     85
5    B  English     88

In [58]:
# #Complete Workflow 
# Load
#   ↓
# Understand
#   ↓
# Check missing values
#   ↓
# Check duplicates
#   ↓
# Check data types
#   ↓
# Clean data
#   ↓
# Select / Filter
#   ↓
# Sort
#   ↓
# Create new columns
#   ↓
# Group & Aggregate
#   ↓
# Merge / Concatenate
#   ↓
# Reshape (melt / pivot)
#   ↓
# Analyze
#   ↓
# Save

#for saving 
df.to_csv("math.csv", index=False)

In [60]:
clean_dataset.to_csv("cleaned_data.csv", index=False)