In [1]:
# 1. Import Pandas
import pandas as pd

In [2]:
# 2. Load the dataset
# For a CSV file:
df = pd.read_csv(r"dataset/College.csv")
#For an Excel file
# df = pd.read_excel("data.xlsx")

In [3]:
# 3. Understand the dataset
# Check the first and last rows:
df.head()

,State,District,University Type,University Name,College Name,College Type,Address,Website,Management,Year of Establishment\n,Specialised in,Location,Unnamed: 12,Upload Year,The Institute Added In Survey Year
0,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Jawaharlal Nehru Rajkeeya Mahavidyalaya (Id: ...,Affiliated College,"Jawaharlal Nehru Rajkeeya Mahavidyalaya, M S ...",jnrm.and.nic.in,Central Government,1967.0,No,Urban,NaN,2019,2010.0
1,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Regional Medical Research Institute (I.C.M.R.)...,Affiliated College,"Post Bag No 13, Dollygunj, Port Blair",http://www.rmrc.res.in,Central Government,1983.0,Medical-Others,Urban,NaN,2019,2010.0
2,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Tagore Government College of Education (Id: C-...,Affiliated College,"M.G. Road, Middle Point, Port Blair - 744101",www.tgce.and.nic.in,State Government,1981.0,Education/Teacher Education,Urban,NaN,2019,2010.0
3,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Zoological Survey of India (Id: C-6560),Affiliated College,"Zoological Survey of India, Andaman & Nicobar ...",www.zsi.gov.in,Central Government,1977.0,Science,Urban,NaN,2019,2010.0
4,Andaman and Nicobar Islands,North and Middle Andaman,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Mahatma Gandhi Govt. College (Id: C-6547),Affiliated College,"Rampur, Mayabunder, Mayabunder",http://mggcm.and.nic.in,Central Government,1990.0,No,Rural,NaN,2019,2010.0

In [4]:
df.tail()

,State,District,University Type,University Name,College Name,College Type,Address,Website,Management,Year of Establishment\n,Specialised in,Location,Unnamed: 12,Upload Year,The Institute Added In Survey Year
47585,West Bengal,Purulia,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,Ramkrishna Mahato Memorial Teachers Training C...,Affiliated College,"VILLAGE- MANAKCHITA, POST OFFICE- BARAGRAM, PO...",www.rmmttcollege.org.in,Private Aided,2015.0,Education/Teacher Education,Rural,NaN,2020,2015.0
47586,West Bengal,Purulia,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,SIMANTA MANBHUM TEACHERS TRAINING COLLEGE (Id:...,Affiliated College,"Chelyama, Chelyama, Raghunathpur",www.smttchelyama.org,Private Un-Aided,2018.0,Education/Teacher Education,Rural,NaN,2020,2019.0
47587,West Bengal,Purulia,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,Sponsored Teachers' Training college (Id: C-44...,Affiliated College,"Deshbandhu Road, P.O : Purulia, Purulia",www.sttcollege.org,Private Aided,1964.0,Education/Teacher Education,Urban,NaN,2020,2010.0
47588,West Bengal,Purulia,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,Vidyasagar Foundation School of Education & Tr...,Affiliated College,"Vill - Tamna, POST - SIMULIA , PIN- 723102, PU...",https://vfset.vidyasagar-foundation.org/,Private Un-Aided,2008.0,Education/Teacher Education,Rural,NaN,2020,2010.0
47589,Generated On: 04/10/2022 03:47:13 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Check the number of rows and columns:
df.shape

(47590, 15)

In [6]:
# Check column names:
df.columns

Index(['State', 'District', 'University Type', 'University Name',
       'College Name', 'College Type', 'Address', 'Website', 'Management',
       'Year of Establishment\n', 'Specialised in', 'Location', 'Unnamed: 12',
       'Upload Year', 'The Institute Added In Survey Year'],
      dtype='str')

In [7]:
# For general Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47590 entries, 0 to 47589
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               47590 non-null  str
 1   District                            47589 non-null  str
 2   University Type                     47589 non-null  str
 3   University Name                     47589 non-null  str
 4   College Name                        47589 non-null  str
 5   College Type                        47589 non-null  str
 6   Address                             44531 non-null  str
 7   Website                             36097 non-null  str
 8   Management                          44531 non-null  str
 9   Year of Establishment
              44297 non-null  float64
 10  Specialised in                      44313 non-null  str
 11  Location                            44531 non-null  str
 12  Unnamed: 12                         0 non-null      float64
 13  Upload Year                         47589 non-null  str
 14  The Institute Added In Survey Year  47589 non-null  float64
dtypes: float64(3), str(12)
memory usage: 5.4 MB

In [8]:
# Get statistical information:
df.describe()

,Year of Establishment\n,Unnamed: 12,The Institute Added In Survey Year
count,44297.000000,0.0,47589.000000
mean,2000.840621,NaN,2012.587216
std,21.768339,NaN,3.683469
min,1.000000,NaN,2010.000000
25%,1997.000000,NaN,2010.000000
50%,2007.000000,NaN,2010.000000
75%,2013.000000,NaN,2015.000000
max,2020.000000,NaN,2022.000000

In [9]:
# 4. Check and handle missing values
# Find missing values:
df.isnull().sum()

State                                     0
District                                  1
University Type                           1
University Name                           1
College Name                              1
College Type                              1
Address                                3059
Website                               11493
Management                             3059
Year of Establishment\n                3293
Specialised in                         3277
Location                               3059
Unnamed: 12                           47590
Upload Year                               1
The Institute Added In Survey Year        1
dtype: int64

In [10]:
#change data type of the column 
df["Upload Year"] = pd.to_numeric(df["Upload Year"], errors="coerce")

df["Upload Year"] = df["Upload Year"].fillna(
    df["Upload Year"].mean().round()
).astype(int)

In [11]:
# Fill missing values:
df["Upload Year"] = df["Upload Year"].fillna(df["Upload Year"].mean())

In [12]:
#for number fill with 0 
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(0)
#for string fill with unknown
string_cols = df.select_dtypes(include='str').columns
df[string_cols] = df[string_cols].fillna("Unknown")

In [13]:
# 5. Check and remove duplicates
# Find duplicates:
df.duplicated().sum()

np.int64(0)

In [14]:
# Remove duplicates:
df = df.drop_duplicates()

In [15]:
df.dropna(inplace=True) #for row deleting missing values

In [16]:
# df.head(5)

In [17]:
# 6. Check and correct data types
# Check data types:
df.dtypes

State                                     str
District                                  str
University Type                           str
University Name                           str
College Name                              str
College Type                              str
Address                                   str
Website                                   str
Management                                str
Year of Establishment\n               float64
Specialised in                            str
Location                                  str
Unnamed: 12                           float64
Upload Year                             int64
The Institute Added In Survey Year    float64
dtype: object

In [18]:
df = df.rename(columns={
    "Year of Establishment\n": "Year_of_Establishment",
    "The Institute Added In Survey Year ": "Inst_added_in_survey_year",
    "Upload Year": "Upload_Year",
    "Specialised in": "Specialised_in",
    "University Type": "University_Type",
    "University Name": "University_Name",
    "College Name": "College_Name",
    "College Type": "College_Type"
})

In [19]:
#clean all automatically
df.columns = (
    df.columns
    .str.strip()
    .str.replace("\n", "", regex=False)
    .str.replace(" ", "_")
)

In [20]:
df.columns

Index(['State', 'District', 'University_Type', 'University_Name',
       'College_Name', 'College_Type', 'Address', 'Website', 'Management',
       'Year_of_Establishment', 'Specialised_in', 'Location', 'Unnamed:_12',
       'Upload_Year', 'The_Institute_Added_In_Survey_Year'],
      dtype='str')

In [21]:
# Drop columns containing missing values or not used :
df = df.drop("Unnamed:_12", axis=1)

In [22]:
df.columns

Index(['State', 'District', 'University_Type', 'University_Name',
       'College_Name', 'College_Type', 'Address', 'Website', 'Management',
       'Year_of_Establishment', 'Specialised_in', 'Location', 'Upload_Year',
       'The_Institute_Added_In_Survey_Year'],
      dtype='str')

In [23]:
df.head(5)

,State,District,University_Type,University_Name,College_Name,College_Type,Address,Website,Management,Year_of_Establishment,Specialised_in,Location,Upload_Year,The_Institute_Added_In_Survey_Year
0,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Jawaharlal Nehru Rajkeeya Mahavidyalaya (Id: ...,Affiliated College,"Jawaharlal Nehru Rajkeeya Mahavidyalaya, M S ...",jnrm.and.nic.in,Central Government,1967.0,No,Urban,2019,2010.0
1,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Regional Medical Research Institute (I.C.M.R.)...,Affiliated College,"Post Bag No 13, Dollygunj, Port Blair",http://www.rmrc.res.in,Central Government,1983.0,Medical-Others,Urban,2019,2010.0
2,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Tagore Government College of Education (Id: C-...,Affiliated College,"M.G. Road, Middle Point, Port Blair - 744101",www.tgce.and.nic.in,State Government,1981.0,Education/Teacher Education,Urban,2019,2010.0
3,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Zoological Survey of India (Id: C-6560),Affiliated College,"Zoological Survey of India, Andaman & Nicobar ...",www.zsi.gov.in,Central Government,1977.0,Science,Urban,2019,2010.0
4,Andaman and Nicobar Islands,North and Middle Andaman,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Mahatma Gandhi Govt. College (Id: C-6547),Affiliated College,"Rampur, Mayabunder, Mayabunder",http://mggcm.and.nic.in,Central Government,1990.0,No,Rural,2019,2010.0

In [24]:
# 8. Select and filter data
# Select one column:
df['College_Name']

0        Jawaharlal Nehru Rajkeeya  Mahavidyalaya (Id: ...
1        Regional Medical Research Institute (I.C.M.R.)...
2        Tagore Government College of Education (Id: C-...
3                  Zoological Survey of India (Id: C-6560)
4                Mahatma Gandhi Govt. College (Id: C-6547)
                               ...
47585    Ramkrishna Mahato Memorial Teachers Training C...
47586    SIMANTA MANBHUM TEACHERS TRAINING COLLEGE (Id:...
47587    Sponsored Teachers' Training college (Id: C-44...
47588    Vidyasagar Foundation School of Education & Tr...
47589                                              Unknown
Name: College_Name, Length: 47590, dtype: str

In [25]:
# Select multiple columns:
df[["College_Name", "State", "District"]]

,College_Name,State,District
0,Jawaharlal Nehru Rajkeeya Mahavidyalaya (Id: ...,Andaman and Nicobar Islands,Nicobars
1,Regional Medical Research Institute (I.C.M.R.)...,Andaman and Nicobar Islands,Nicobars
2,Tagore Government College of Education (Id: C-...,Andaman and Nicobar Islands,Nicobars
3,Zoological Survey of India (Id: C-6560),Andaman and Nicobar Islands,Nicobars
4,Mahatma Gandhi Govt. College (Id: C-6547),Andaman and Nicobar Islands,North and Middle Andaman
...,...,...,...
47585,Ramkrishna Mahato Memorial Teachers Training C...,West Bengal,Purulia
47586,SIMANTA MANBHUM TEACHERS TRAINING COLLEGE (Id:...,West Bengal,Purulia
47587,Sponsored Teachers' Training college (Id: C-44...,West Bengal,Purulia
47588,Vidyasagar Foundation School of Education & Tr...,West Bengal,Purulia
47589,Unknown,Generated On: 04/10/2022 03:47:13 PM,Unknown

In [26]:
# Filter rows:
df[df["State"] == "Bihar"]

,State,District,University_Type,University_Name,College_Name,College_Type,Address,Website,Management,Year_of_Establishment,Specialised_in,Location,Upload_Year,The_Institute_Added_In_Survey_Year
3328,Bihar,Araria,State Public University,"Aryabhatta Knoweledge University , Patna (Id: ...",Moti Babu Institute of Technology (Id: C-49556),Affiliated College,"Industrial Estate, NH - 57, Forbesganj",www.mbit.in,Private Un-Aided,2014.0,Engineering & Technology,Rural,2020,2014.0
3329,Bihar,Araria,State Public University,"Aryabhatta Knoweledge University , Patna (Id: ...","Shri Phanishwar Nath Renu Engineering College,...",Affiliated College,"RENU GRAM SIMRAHA, P.O. SIMRAHA, Araria",https://www.spnrecararia.org.in,State Government,2019.0,No,Rural,2020,2019.0
3330,Bihar,Araria,State Public University,"PURNEA UNIVERSITY, PURNIA (Id: U-0999)","A. M. Degree College, Araria (Id: C-29590)",Affiliated College,"FAZL ABAD, ARARIA, Araria",Unknown,Private Aided,1985.0,No,Rural,2020,2010.0
3331,Bihar,Araria,State Public University,"PURNEA UNIVERSITY, PURNIA (Id: U-0999)","Araria College, Araria (Id: C-29616)",Constituent / University College,"Araria, Jayprakash Nagar, Araria, Araria",www.arariacollegebnmu.com,University,1973.0,No,Urban,2020,2010.0
3332,Bihar,Araria,State Public University,"PURNEA UNIVERSITY, PURNIA (Id: U-0999)","C. K. M. Law College, Araria (Id: C-29591)",Affiliated College,"Chandra Kishore Mishra Law College, Near Girls...",Unknown,Private Aided,1982.0,Law,Urban,2020,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4434,Bihar,Vaishali,State Public University,"Babasaheb Bhimrao Ambedkar Bihar University, M...",VEDANT INSTITUTE OF EDUCATION AND TECHNOLOGY ...,Affiliated College,"SAHPUR TIWARI TOTHAN LALGANJ, VAISHALI, LALGANJ",www.vedantcollege.co.in,Private Un-Aided,2011.0,No,Rural,2020,2019.0
4435,Bihar,Vaishali,State Public University,"Babasaheb Bhimrao Ambedkar Bihar University, M...","Virchand Patel Smarak College, Desri, Vaishali...",Affiliated College,"DESARI, DESARI, HAJIPUR",https://bpscollege.in/,Private Aided,1971.0,No,Rural,2020,2010.0
4436,Bihar,Vaishali,State Public University,"Babasaheb Bhimrao Ambedkar Bihar University, M...",VISHUN RAJDEO TEACHERS TRAINING COLLEGE (Id: C...,Affiliated College,"Plot No. 685,1,2 Street No. 12, KIRATPUR RAJAR...",www.vrttcollege.com,Private Un-Aided,2008.0,Education/Teacher Education,Rural,2020,2013.0
4437,Bihar,Vaishali,State Public University,Kameshwar Singh Darbhanga Sanskrit Vishwavidya...,"S.R.P.Skt.College,Patepur,Vaishali (Id: C-9635)",Affiliated College,"Patepur,Vashali,Bihar, Pincode-843114, Hajipur",Unknown,University,1933.0,No,Rural,2020,2010.0
4438,Bihar,Vaishali,State Public University,Maulana Mazharul Haque Arabic & Persian Univer...,ROYAL HERITAGE COLLEGE OF EDUCATION (Id: C-57691),Affiliated College,"Plot no - 1092, Street/Road - Mahnar Road, Raj...",www.royalheritagecollege.com,Private Un-Aided,2016.0,No,Rural,2020,2016.0

In [27]:
# Multiple conditions:
df[(df["State"] == "Bihar") & (df["District"] == "Bhagalpur")]

,State,District,University_Type,University_Name,College_Name,College_Type,Address,Website,Management,Year_of_Establishment,Specialised_in,Location,Upload_Year,The_Institute_Added_In_Survey_Year
3421,Bihar,Bhagalpur,State Public University,"Aryabhatta Knoweledge University , Patna (Id: ...",Bhagalpur College of Engineering (Id: C-42781),Affiliated College,"P.O - SABOUR, P.S - INDUSTRIAL AREA (ZERO MILE...",www.bcebhagalpur.ac.in,State Government,1960.0,Engineering & Technology,Rural,2020,2010.0
3422,Bihar,Bhagalpur,State Public University,"Aryabhatta Knoweledge University , Patna (Id: ...",Jawahar Lal Nehru Medical College & Hospital (...,Affiliated College,"S. R. R. PATH, BHAGALPUR",www.jlnmcbgp.org,State Government,1971.0,Medical-Allopathy,Urban,2020,2010.0
3423,Bihar,Bhagalpur,State Public University,"Bihar Agriculture University, Sabour (Id: U-0060)","Bihar Agricultural College, Sabour (Id: C-8347)",Constituent / University College,"Assoc.Dean-cum-Principal,Bihar Agricultural Co...",www.bausabour.ac.in,University,1908.0,Agriculture,Rural,2020,2010.0
3424,Bihar,Bhagalpur,State Public University,Kameshwar Singh Darbhanga Sanskrit Vishwavidya...,"Government Sanskrit College, Bhagalpur (Id: C-...",Constituent / University College,"P.O-T.N.B.College,Bhagalpur, Bhagalpur, Bhagalpur",www.gscbhagalpur.com,University,1954.0,Sanskrit,Urban,2020,2010.0
3425,Bihar,Bhagalpur,State Public University,Kameshwar Singh Darbhanga Sanskrit Vishwavidya...,"SHREE MAHANTH VAIDEHI SHARAN SANSKRIT COLLEGE,...",Affiliated College,", ,",Unknown,Private Un-Aided,1984.0,SANSKRIT,Rural,2020,2020.0
3426,Bihar,Bhagalpur,State Public University,Makhanlal Chaturvedi National University of Jo...,DR. ZAKIR HUSSAIN INSTITUTE OF NON FORMAL & CO...,Recognized Center,Unknown,Unknown,Unknown,0.0,Unknown,Unknown,2020,2010.0
3427,Bihar,Bhagalpur,State Public University,Makhanlal Chaturvedi National University of Jo...,DR. ZAKIR HUSSAIN INSTITUTE OF NON FORMAL & CO...,Recognized Center,Unknown,Unknown,Unknown,0.0,Unknown,Unknown,2020,2010.0
3428,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",A.K.GOPALAN DEGREE COLLEGE (Id: C-61208),Affiliated College,"TARAPUR ROAD, SULTANGANJ, SULTANGANJ",www.akgopalandegreecollege.in,Private Aided,1980.0,No,Rural,2020,2018.0
3429,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",ARJUN COLLEGE OF EDUCATION (Id: C-60255),Affiliated College,"NH-31, NEAR POWER GRID, MADRAUNI, NAUGACHIA, B...",www.arjunmemorialtrust.com,Private Un-Aided,2018.0,Education/Teacher Education,Rural,2020,2018.0
3430,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Banarsilal Saraf Commerce College, Naugachia (...",Affiliated College,"NAUGACHIA, NAUGACHIA, NAUGACHIA",www.blsccollegenaugachia.com,University,1985.0,No,Urban,2020,2010.0
3431,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","B.N. College, Bhagalpur (Id: C-17619)",Constituent / University College,"LOWER NATHNAGAR ROAD, PO- T.N.B. COLLEGE, BHAG...",www.bncollegebgp.ac.in,University,1960.0,No,Urban,2020,2010.0
3432,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","College of Teacher Education, Bhagalpur (Id: C...",Affiliated College,"College of Teacher Education(CTE),Ghantaghar, ...",ctebhagalpur.in,State Government,1954.0,Education/Teacher Education,Urban,2020,2013.0
3433,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",D.L.S SHIKSHA MAHAVIDHYALAY (Id: C-60578),Affiliated College,"SIDHARI BADLUGANJ BARAHAT, ISHIPUR, BHAGALPUR",www.dlsshikshamahavidyalay.com,University,2017.0,Education/Teacher Education,Rural,2020,2018.0
3434,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","GB College, Naugachia (Id: C-17649)",Constituent / University College,"G.B College, Naugachia, Naugachia",www.gbcweb.in,University,1958.0,No,Rural,2020,2010.0
3435,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","JP College, Narayanpur (Id: C-17635)",Constituent / University College,"Principal, J.P.COLLEGE, Narayanpur",www.jpcollegenarayanpur.in,University,1952.0,No,Rural,2020,2010.0
3436,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","LNBJ Mahila College, Bhramarpur (Id: C-17642)",Affiliated College,"AT- BHRAMARPUR, PO - BHRAMARPUR, THANA - BIHPU...",Unknown,University,1980.0,No,Rural,2020,2010.0
3437,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Mahadeo Singh College, Bhagalpur (Id: C-17653)",Affiliated College,"KILAGHAT SARAI, BHAGALPUR, KILAGHAT SARAI BHAG...",www.mscollegebgp.in,Private Aided,1983.0,No,Urban,2020,2010.0
3438,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","MAM College, Naugachia (Id: C-17651)",Constituent / University College,"Harnath chak, Ward no 03, Naugachia",mamcollegenna.org,University,1982.0,No,Rural,2020,2010.0
3439,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Marwari College, Bhagalpur (Id: C-17620)",Constituent / University College,"Post- TNB College, Bhagalpur, Near TM Bhagalpu...",www.marwaricollegebgp.ac.in,University,1941.0,No,Urban,2020,2010.0
3440,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","M.M. College, Bhagalpur (Id: C-17654)",Affiliated College,"Lower Nathnagar road,Asanandpur,Bhagalpur, do,...",Unknown,Local Body,1981.0,No,Urban,2020,2010.0
3441,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",MOD NARAYAN MAHAVIDYALAYA AMBA SHAHKUND BHAGAL...,Affiliated College,Unknown,Unknown,Unknown,0.0,Unknown,Unknown,2020,2021.0
3442,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Murarka College, Sultanganj (Id: C-17645)",Constituent / University College,"At & Po- Sultanganj, At & Po- Sultanganj, Bhag...",www.murarkacollegesult.in,University,1955.0,No,Rural,2020,2010.0
3443,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",NEW HORIZON COLLEGE OF EDUCATION (Id: C-59528),Affiliated College,"Shahpur-Tamauni, Simaria, Kajrely, Amarpur Roa...",www.nhcebhagalpur.com,Private Un-Aided,2014.0,Education/Teacher Education,Rural,2020,2017.0
3444,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",PNA SCIENCE COLLEGE (Id: C-65521),Affiliated College,Unknown,Unknown,Unknown,0.0,Unknown,Unknown,2020,2021.0
3445,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",Puranmal Bajoria Teachers Training College (Id...,Affiliated College,"Nargakothi, Champanagar, Bhagalpur",www.pbttcollege.com,Private Un-Aided,2011.0,Education/Teacher Education,Urban,2020,2015.0
3446,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Sabour College, Sabour (Id: C-17641)",Constituent / University College,"Sabour College, Sabour, Sabour College, Sabour...",www.sabourcollege.com,University,1973.0,No,Rural,2020,2010.0
3447,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",SATYADEV MAHAVIDYALAYA GOURIPUR (Id: C-65761),Affiliated College,Unknown,Unknown,Unknown,0.0,Unknown,Unknown,2020,2021.0
3448,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","S. Jhunjhunwala Mahila College, Bhagalpur (Id:...",Affiliated College,"AT-RAMESHWER NARAYAN AGRAWAL PATH, CHUNIHARI T...",sjmcollegebgp.in,Local Body,1971.0,No,Urban,2020,2010.0
3449,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","S.M. College, Bhagalpur (Id: C-17650)",Constituent / University College,"Chhoti Khanjarpur, Bhagalpur, Bhagalpur",www.smcollege.ac.in,University,1949.0,No,Urban,2020,2010.0
3450,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","SSV College, Kahalgaon (Id: C-17623)",Constituent / University College,"P.O. : Kahalgaon, Dist. : Bhagalpur, Kahalgaon",www.ssvcollegekahalgaon.org,State Government,1967.0,No,Rural,2020,2010.0
3451,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","Tarar College, Tarar (Id: C-17647)",Affiliated College,"AT+POST-TATAR, P.S-SANHOULA, BHAGALPUR",tararcollegetarar.com,Private Aided,1984.0,No,Rural,2020,2010.0
3452,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)",TEACHERs TRAINING COLLEGE (Id: C-48047),Affiliated College,"Plot No.-D-9,10 & Ns Plot, Large Industrial Es...",www.ttcb.co.in,Private Un-Aided,2012.0,Education/Teacher Education,Urban,2020,2012.0
3453,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","T.N.B. College, Bhagalpur (Id: C-17621)",Constituent / University College,"Lower Nathhnagar Road, Bhagalpur, Bhagalpur",www.tnbcollege.org,University,1887.0,No,Urban,2020,2010.0
3454,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","TNB Law College, Bhagalpur (Id: C-17648)",Constituent / University College,"Tilkamanjhi, Barari Road,, Bhagalpur, Bhagalpur",www.tnblawcollegebgp.org,University,1959.0,Law,Urban,2020,2010.0
3455,Bihar,Bhagalpur,State Public University,"T.M. Bhagalpur University, Bhagalpur (Id: U-0076)","V. B. College of Education, Bhagalpur (Id: C-5...",Affiliated College,"Deekshapuram, DPS Campus, Sabour, Bhagalpur",www.vbcebhagalpur.in,Private Un-Aided,2007.0,Education/Teacher Education,Rural,2020,2017.0

In [28]:
# 9. Sort the data
# Ascending:
df.sort_values("State")

,State,District,University_Type,University_Name,College_Name,College_Type,Address,Website,Management,Year_of_Establishment,Specialised_in,Location,Upload_Year,The_Institute_Added_In_Survey_Year
0,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Jawaharlal Nehru Rajkeeya Mahavidyalaya (Id: ...,Affiliated College,"Jawaharlal Nehru Rajkeeya Mahavidyalaya, M S ...",jnrm.and.nic.in,Central Government,1967.0,No,Urban,2019,2010.0
7,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",ANDAMAN LAW COLLEGE (Id: C-63976),Affiliated College,"Andaman Law College, Transport Bhawan, Phoenix...",https://andamanlawcollege.andaman.gov.in,State Government,2016.0,Law,Urban,2020,2020.0
6,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",ANDAMAN COLLEGE (ANCOL) (Id: C-50934),Affiliated College,"CHAKKARGOAN, SOUTH ANDAMAN, PORT BLAIR",www.ancol.andaman.gov.in,Central Government,2014.0,No,Urban,2020,2014.0
5,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Andaman and Nicobar inslands Institute of medi...,Affiliated College,"DHS Annexe Building, Atlanta Point, Port Blair",www.aniims.org,Central Government,2015.0,Medical-Allopathy,Urban,2019,2018.0
8,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Dr.B.R. Ambedkar Institute of Technology (Id: ...,Affiliated College,"Pahargaon, Junglighat Post office Pin 744103, ...",http://dbragpt.andaman.gov.in,Central Government,1984.0,No,Urban,2020,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46553,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,Gangarampur B. Ed. College (Id: C-42678),Affiliated College,"P.O. Kaldighi, Dist. Dakshin Dinajpur, P.S. Ga...",www.gmpbedcollege.in,Private Un-Aided,2005.0,Education/Teacher Education,Urban,2020,2010.0
46552,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,FUNDAMENTAL INSTITUTE OF TEACHERS TRAINING (Id...,Affiliated College,"VILL- BARAHARA (DHITOLHAT), P.O. + P.S.- BANSH...",www.dhet.in,Private Aided,2016.0,Education/Teacher Education,Rural,2020,2017.0
46551,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,EDUCITY COLLEGE OF EDUCATION (Id: C-58383),Affiliated College,"VILL-KUSHMANDI, P.O. & P.S-KUSHMANDI, KUSHMANDI",https://www.educitycollege.org,Private Aided,2015.0,Education/Teacher Education,Rural,2020,2017.0
46525,West Bengal,Darjeeling,State Public University,"North Bengal University, Darjeeling (Id: U-0579)","SOUTH FIELD COLLEGE, DARJEELING (Id: C-45338)",Affiliated College,"Mall Road, Darjeeling, Darjeeling",www.southfieldcollege.org,State Government,1960.0,No,Urban,2020,2011.0
46076,West Bengal,24 Paraganas North,State Public University,Maulana Abul Kalam Azad University of Technolo...,Narula Institute of Technology 127 (Id: C-6257),Affiliated College,"81, Nilgunj Road, Agarpara, Kolkata - 700109, ...",www.nit.ac.in,Private Aided,2001.0,Engineering & Technology,Urban,2020,2010.0

In [29]:
#Descending
df.sort_values("State", ascending=False)

,State,District,University_Type,University_Name,College_Name,College_Type,Address,Website,Management,Year_of_Establishment,Specialised_in,Location,Upload_Year,The_Institute_Added_In_Survey_Year
46077,West Bengal,24 Paraganas North,State Public University,Maulana Abul Kalam Azad University of Technolo...,Narula Institute of Technology 305 (Id: C-6140),Affiliated College,"81, Nilgunj Road, Agarpara,Kolkata - 700109, W...",www.nit.ac.in,Private Un-Aided,2004.0,Management,Urban,2020,2010.0
46526,West Bengal,Darjeeling,State Public University,"North Bengal University, Darjeeling (Id: U-0579)","ST. JOSEPH'S COLLEGE, DARJEELING (Id: C-45349)",Constituent / University College,"P. O. NORTH POINT, DARJEELING",www.sjcdarjeeling.edu.in,State Government,1927.0,No,Urban,2020,2011.0
46552,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,FUNDAMENTAL INSTITUTE OF TEACHERS TRAINING (Id...,Affiliated College,"VILL- BARAHARA (DHITOLHAT), P.O. + P.S.- BANSH...",www.dhet.in,Private Aided,2016.0,Education/Teacher Education,Rural,2020,2017.0
46553,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,Gangarampur B. Ed. College (Id: C-42678),Affiliated College,"P.O. Kaldighi, Dist. Dakshin Dinajpur, P.S. Ga...",www.gmpbedcollege.in,Private Un-Aided,2005.0,Education/Teacher Education,Urban,2020,2010.0
46554,West Bengal,Dinajpur Dakshin,State Public University,THE WEST BENGAL UNIVERSITY OF TEARCHERS TRAINI...,RANI PRIMARY TEACHERS TRAINING INSTITUTE (Id:...,Affiliated College,"VILL-DAKSHIN BAHADURPUR, P.O-DANGRAM, P.S-HARI...",www.raniptti.org,Private Un-Aided,2017.0,Education/Teacher Education,Rural,2020,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Regional Medical Research Institute (I.C.M.R.)...,Affiliated College,"Post Bag No 13, Dollygunj, Port Blair",http://www.rmrc.res.in,Central Government,1983.0,Medical-Others,Urban,2019,2010.0
6,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",ANDAMAN COLLEGE (ANCOL) (Id: C-50934),Affiliated College,"CHAKKARGOAN, SOUTH ANDAMAN, PORT BLAIR",www.ancol.andaman.gov.in,Central Government,2014.0,No,Urban,2020,2014.0
7,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",ANDAMAN LAW COLLEGE (Id: C-63976),Affiliated College,"Andaman Law College, Transport Bhawan, Phoenix...",https://andamanlawcollege.andaman.gov.in,State Government,2016.0,Law,Urban,2020,2020.0
8,Andaman and Nicobar Islands,South Andamans,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Dr.B.R. Ambedkar Institute of Technology (Id: ...,Affiliated College,"Pahargaon, Junglighat Post office Pin 744103, ...",http://dbragpt.andaman.gov.in,Central Government,1984.0,No,Urban,2020,2010.0
0,Andaman and Nicobar Islands,Nicobars,Central University,"Pondicherry Univeristy, Puducherry (Id: U-0369)",Jawaharlal Nehru Rajkeeya Mahavidyalaya (Id: ...,Affiliated College,"Jawaharlal Nehru Rajkeeya Mahavidyalaya, M S ...",jnrm.and.nic.in,Central Government,1967.0,No,Urban,2019,2010.0

In [30]:
# 10. Create or modify columns
# Create a new column:
# df["Total"] = df["A"] + df["B"] + df["C"]

#calculate Average
#df["Average"] = df["Total"] / 3

In [31]:
# 11. Group and aggregate
# Group data:
df.groupby(["State"])

In [32]:
# 12. Use transform() when you need the original shape
# Unlike groupby().mean(), transform() gives a result that can be directly added back to the original DataFrame.
# df["Avg"] = df.groupby("State")["Year"].transform("mean")

# 13. Count values
df["State"].value_counts()

State
Uttar Pradesh                                   8351
Maharashtra                                     4909
Karnataka                                       4563
Rajasthan                                       4041
Madhya Pradesh                                  3698
Gujarat                                         2847
Tamil Nadu                                      2788
Andhra Pradesh                                  2669
Telangana                                       2093
Kerala                                          1548
West Bengal                                     1546
Odisha                                          1277
Haryana                                         1114
Bihar                                           1111
Punjab                                          1086
Chhattisgarh                                     921
Assam                                            608
Uttarakhand                                      499
Jharkhand                                        361
Jammu and Kashmir                                360
Himachal Pradesh                                 357
Delhi                                            188
Manipur                                          107
Puducherry                                        91
Meghalaya                                         82
Goa                                               73
Nagaland                                          72
Tripura                                           55
Arunachal Pradesh                                 42
Mizoram                                           40
Sikkim                                            30
Chandigarh                                        26
The Dadra and Nagar Haveli and Daman and Diu      21
Andaman and Nicobar Islands                        9
Ladakh                                             3
Lakshadweep                                        3
Generated On: 04/10/2022 03:47:13 PM               1
Name: count, dtype: int64

In [33]:
# 14. Combine datasets
# Merge:
# df = pd.merge(df1, df2, on="ID", how="inner")
# Concatenate:
# df = pd.concat([df1, df2], axis=0)

In [34]:
# 15. Reshape the dataset
# Wide → Long:
# Long → Wide:

In [35]:
# # 16. Analyze the cleaned data
# df["A"].mean()
# df["A"].max()
# df["A"].min()
# df["A"].median()

In [36]:
#for analyzing 
df.describe()

       Year_of_Establishment   Upload_Year  The_Institute_Added_In_Survey_Year
count           47590.000000  47590.000000                        47590.000000
mean             1862.392036   2019.828767                         2012.544925
std               508.224391      0.791930                            9.933792
min                 0.000000   2010.000000                            0.000000
25%              1992.000000   2020.000000                         2010.000000
50%              2006.000000   2020.000000                         2010.000000
75%              2012.000000   2020.000000                         2015.000000
max              2020.000000   2020.000000                         2022.000000

In [37]:
# 17. Save the final dataset
# Save as CSV:
df.to_csv(r"dataset/cleaned_College.csv", index=False)

In [38]:
# Load
#   ↓
# Understand
#   ↓
# Check missing values
#   ↓
# Check duplicates
#   ↓
# Check data types
#   ↓
# Clean data
#   ↓
# Select / Filter
#   ↓
# Sort
#   ↓
# Create new columns
#   ↓
# Group & Aggregate
#   ↓
# Merge / Concatenate
#   ↓
# Reshape (melt / pivot)
#   ↓
# Analyze
#   ↓
# Save